Algoritmo "semnome"

Var

  dia:inteiro

Inicio

   escreval("Digite o número de 1 até 7: ")
   leia(dia)
   
   escolha(dia)
   caso 1
   escreval("Domingo")
   caso 2
   escreval("Segunda-Feira")
   caso 3
   escreval("Terça-Feira")
   caso 4
   escreval("Quarta-Feira")
   caso 5
   escreval("Quinta-Feira")
   caso 6
   escreval("Sexta-Feira")
   caso 7
   escreval("Sábado")
   outrocaso
   escreval("Esse dia não existe!")
   fimescolha

Fimalgoritmo