Algoritmo "Escolha SE"

Var

 cor:caractere

Inicio

   escreval("Qual é a sua cor preferida? ")
   leia(cor)

   escolha(cor)
   
    caso "AZUL"
      escreval("Sua cor favorita é azul!")
    caso "VERMELHO"
      escreval("Sua cor favorita é vermelho!")
    caso "AMARELO"
      escreval("Sua cor favorita é amarelo!")
    outrocaso
      escreval("Sua cor favorita não foi localizada na minha base de dados! ERRO #404")
      
   fimescolha

Fimalgoritmo