Algoritmo "EX Retângulo"

Var

  numeroA:real
  numeroL:real
  numeroR:real

Inicio

     escreval("Olá, eu irei te ajudar a calcular a área de um retângulo. Por favor digite a altura do retângulo: ")
     leia(numeroA)
     
     escreval("Ótimo, agora insira a largura do retângulo: ")
     leia(numeroL)
     
     numeroR <- numeroA * numeroL
     
     escreval("Perfeito! a área do retângulo é: ", numeroR, "m²")
     
     
     
Fimalgoritmo